### ISSUE TITLE
The level calculator is slow

### ISSUE THREAD

**Issue by JoseVarelaP** [JoseVarelaP/SM5-GrooveNights#4]
As the title mentions. While it is accurate, it takes a while to process all of its information to just display a bar with a certain experience level.

2 ways to go at this:

- Make the level display a toggle, like the EXP Counter, so if anyone who doesn't want to use it, just needs to turn it off, or is already off by default.
- Redo the system to not rely so much on fetching the same kind of data over and over every time its non-existant or a player has completed a song.

**Comment by JoseVarelaP** [comment]
https://github.com/JoseVarelaP/SM5-GrooveNights/commit/efb06c8d1a48006520890e217518b7b94f9bca31

Changes perfomed in this update *should* make the calculation faster by caching the data as soon as possible and only updating it when it needs to.

**Comment by Horsey-** [comment]
it's more than just the level calculator that's makes the engine chug; GetTotalStepsWithTopGrade() is incredibly slow because it is just inefficient

```
for (Song *pSong : SONGMAN->GetAllSongs())
    {
        if( !pSong->NormallyDisplayed() )
            continue;    // skip

        for (Steps *pSteps : pSong->GetAllSteps())
        {
            if( pSteps->m_StepsType != st )
                continue;    // skip

            if( pSteps->GetDifficulty() != d )
                continue;    // skip

            const HighScoreList &hsl = GetStepsHighScoreList( pSong, pSteps );
            if( hsl.vHighScores.empty() )
                continue;    // skip

            if( hsl.vHighScores[0].GetGrade() == g )
                iCount++;
        }
    }
```

Cube added a new function `GetTotalScoresWithGrade()` which is far more efficient with the caveat that all scores are counted on a player's profile, not just ones which exist in SONGMAN. 

```
local quads = PROFILEMAN:GetProfile(player):GetTotalScoresWithGrade('Grade_Tier01')
local tristars = PROFILEMAN:GetProfile(player):GetTotalScoresWithGrade('Grade_Tier02')
local doublestars = PROFILEMAN:GetProfile(player):GetTotalScoresWithGrade('Grade_Tier03')
local singlestars = PROFILEMAN:GetProfile(player):GetTotalScoresWithGrade('Grade_Tier04')
```

**Comment by JoseVarelaP** [comment]
Yep, had a test with it on a dev build of OutFox, it is just night and day.
At this point I would either just make a compatibility layer for anything that doesn't have the function available or just cut out to avoid the process of having the old methods still.

**Comment by JoseVarelaP** [comment]
Issued a commit that makes use of the new function. https://github.com/JoseVarelaP/SM5-GrooveNights/commit/182248ba6738c541a3e8ca2bb32afbb04b031c2a
